package message;

public enum ClientMessageType {
	DISCONNECTED,
	CONNECTION,
	LOGIN_VISITOR,
	LOGIN_SUBSCRIBER,
	LOGIN_EMPLOYEE,
	VALIDATE_DATE,
	UPDATE_CAPACITY,
	UPDATE_DIFFERENCE,
	UPDATE_DURATION,
	APPROVE_CAPACITY,
	APPROVE_DIFFERENCE,
	APPROVE_DURATION,
	PRODUCE_REPORT

}
