package message;

public enum ClientMessageType {
	DISCONNECTED,
	LOGOUT,
	CONNECTION,
	LOGIN_VISITOR,
	LOGIN_SUBSCRIBER,
	LOGIN_EMPLOYEE,
	GET_PARKS,
	VALIDATE_DATE,
	UPDATE_CAPACITY,
	UPDATE_DIFFERENCE,
	UPDATE_DURATION,
	APPROVE_CAPACITY,
	APPROVE_DIFFERENCE,
	APPROVE_DURATION,
	VISITOR_REPORT,
	ORDER,
	PARAMETER_UPDATE,
	WAITING_LIST,
	INCOME_REPORT,
	PICK_AVAILABLE_DATES,
	DISCOUNT_REQUEST,
	DEP_MNG_CANCELLATION_REPORT,
	OCCASIONAL_ORDER,
	PARK_MNG_CAPACITY_REPORT,
	GET_ORDERS_BY_ID,
	CANCEL_ORDER,
	APPROVE_ORDER,
	DEP_MNG_VISITION_REPORT,
	ACTIVATE_ORDER_FROM_WATING_LIST
	

}
