package message;

public enum ClientMessageType {
	DISCONNECTED,
	CONNECTION,
	VALIDATE_VISITOR,
	VALIDATE_SUBSCRIBER,
	VALIDATE_EMPLOYEE,
	VALIDATE_DATE,
	UPDATE_CAPACITY,
	UPDATE_DIFFERENCE,
	UPDATE_DURATION,
	APPROVE_CAPACITY,
	APPROVE_DIFFERENCE,
	APPROVE_DURATION,
	PRODUCE_REPORT

}
