package message;

public enum ServerMessageType {
	LOGIN,
	LOGOUT_SUCCESS,
	AVAILABLE_DATES,
	PARK_LIST,
	PARK_VISITATION_REPORT,
	PARK_CAPACITY_REPORT,
	PARK_INCOME_REPORT,
	DEPARTMENT_VISITATION_REPORT,
	DEPARTMENT_CANCELLATION_REPORT,
	SERVER_ERROR,
	ORDER_SUCCESS,
	ORDER_FAILURE,
	WATING_LIST

}
